/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.Manager;

import com.mycompany.Database.DBConnection;
import com.mycompany.Database.ManagerSession;
import com.mycompany.Welcome.Welcome;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JoeAlpha
 */
public class Page1_ManagerLogin extends javax.swing.JFrame {

    /**
     * Creates new form Page1_AdminLogin
     */
    public Page1_ManagerLogin() {
        initComponents();

        // center the form
        this.setLocationRelativeTo(this);
        
        BackToHomePage.setBackground(Color.white);
    }
    
    // create a variable for connection to the database     
    PreparedStatement sqlQueryCheck;     
    PreparedStatement sqlQueryLogin;
    ResultSet res;
    Connection conn;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        passwordLine = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        emailLine = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblExit = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BackToHomePage = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.textHighlight);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Milimani Greens Hotel");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 330, 50));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sign in to your account");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 310, -1));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lock.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 35));

        passwordLine.setBackground(java.awt.Color.darkGray);
        passwordLine.setText("jTextField2");
        passwordLine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(passwordLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, 255, 1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setForeground(java.awt.Color.gray);
        txtPassword.setText("yourpassword");
        txtPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 1));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 3, 220, 30));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 280, 50));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Email Icon.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(java.awt.Color.gray);
        txtEmail.setText("someone@newmail.com");
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 1));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel4.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 3, 220, 30));

        emailLine.setBackground(java.awt.Color.darkGray);
        emailLine.setText("jTextField2");
        emailLine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel4.add(emailLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, 255, 1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 280, 50));

        btnLogin.setBackground(java.awt.SystemColor.textHighlight);
        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogin.setForeground(java.awt.Color.white);
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 240, 120, 35));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 350, 300));

        lblExit.setBackground(java.awt.Color.white);
        lblExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setOpaque(true);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jPanel1.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 1, 30, -1));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hotel Mgt.png"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 280));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 19)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Milimani Greens Hotel");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 350, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("A hotel room is a substitute for the home. ");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 350, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 350, 340));

        BackToHomePage.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        BackToHomePage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BackToHomePage.setText("<");
        BackToHomePage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackToHomePage.setOpaque(true);
        BackToHomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackToHomePageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackToHomePageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackToHomePageMouseExited(evt);
            }
        });
        jPanel1.add(BackToHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 1, 30, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // exit the system
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        lblExit.setForeground(Color.white);
        lblExit.setBackground(Color.red);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        lblExit.setForeground(Color.black);
        lblExit.setBackground(Color.white);
    }//GEN-LAST:event_lblExitMouseExited

    private void BackToHomePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackToHomePageMouseClicked
        // Back to homePage
        Welcome homePage = new Welcome();
        this.dispose();
        homePage.setVisible(true);
    }//GEN-LAST:event_BackToHomePageMouseClicked

    private void BackToHomePageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackToHomePageMouseEntered
        BackToHomePage.setForeground(Color.black);
        BackToHomePage.setBackground(Color.gray);
    }//GEN-LAST:event_BackToHomePageMouseEntered

    private void BackToHomePageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackToHomePageMouseExited
        BackToHomePage.setForeground(Color.black);
        BackToHomePage.setBackground(Color.white);
    }//GEN-LAST:event_BackToHomePageMouseExited

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // operation that occur when this field is clicked
        if(txtEmail.getText().trim().toLowerCase().equals("someone@newmail.com")){
            txtEmail.setText("");
            txtEmail.setForeground(Color.black);
            emailLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // operation that occur when this field is not clicked
        if(txtEmail.getText().trim().equals("") || txtEmail.getText().trim().equals("someone@newmail.com")){
            txtEmail.setText("someone@newmail.com");
            txtEmail.setForeground(Color.gray);
            emailLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        // operation that occur when this field is clicked
        String pwd = String.valueOf(txtPassword.getPassword());   // get the password in text format (not in password/**** format)

        if(pwd.trim().toLowerCase().equals("yourpassword")){
            txtPassword.setText("");
            txtPassword.setForeground(Color.black);
            passwordLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        // operation that occur when this field is not clicked
        String pwd = String.valueOf(txtPassword.getPassword());   // get the password in text format (not in password/**** format)

        if(pwd.trim().equals("") || pwd.trim().equals("yourpassword")){
            txtPassword.setText("yourpassword");
            txtPassword.setForeground(Color.gray);
            passwordLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // operation for login inside the system
        
        // start by initializing the session 
        ManagerSession startSession = new ManagerSession(); 
        
        String userEmail = txtEmail.getText();     
        String userPass = String.valueOf(txtPassword.getPassword());
        
        if(userEmail.trim().equals("") || userEmail.trim().equals("someone@newmail.com")){
            JOptionPane.showMessageDialog(this, "Please Fill in your Email", "Try again", JOptionPane.ERROR_MESSAGE);
            return;
        } else if(userPass.trim().equals("") || userPass.trim().equals("yourpassword")){
            JOptionPane.showMessageDialog(this, "Please Fill in your Password", "Try again", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            try {
                // checking if user credential already exist
                conn = DBConnection.setConnection();
                sqlQueryCheck = conn.prepareStatement("select * from tbl_managers where email=?");
                sqlQueryCheck.setString(1, userEmail);
                res = sqlQueryCheck.executeQuery();
                
                if(!res.isBeforeFirst()) {
                    // if the credential dont match with the one in the database
                    JOptionPane.showMessageDialog(this, "Invalid Email", "Please Try again", JOptionPane.ERROR_MESSAGE);

                    // clearing the neccessary field to allow the user to key in valid Cridentials  
                    txtEmail.setText(""); 
                    txtEmail.requestFocus();
                    return;     
                } else {
                    // if the email match with the one in the database then check the password 
                    while(res.next()) {
                        // retrieve the password in the db
                        String retrievePass = res.getString("password");
                        
                        // checking if password provided matches with the one in the database

                        if (retrievePass.equals(userPass)) {
                            // using the login credentials to get the user session
                            if(startSession.isLogin(userEmail, userPass, this)){
                                // updating users status to online
                                conn = DBConnection.setConnection();
                                sqlQueryLogin = conn.prepareStatement("update tbl_managers SET status='Online' WHERE email=? ");
                                sqlQueryLogin.setString(1, userEmail);

                                if (sqlQueryLogin.executeUpdate() != 0) {
                                    // redirect  to Dashboard 
                                    new Page2_Dashboard().setVisible(true);
                                    this.dispose();
                                }
                            }
                            else {
                                JOptionPane.showMessageDialog(this, "Please type correct Email or Password");
                            }
                        } else {
                            // if the credential dont match with the one in the database
                            JOptionPane.showMessageDialog(this, "Invalid Password", "Please Try again", JOptionPane.ERROR_MESSAGE);
                            
                            // clearing the neccessary field to allow the user to key in valid Cridentials  
                            txtPassword.setText(""); 
                            txtPassword.requestFocus();
                            return; 
                        }
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(Page1_ManagerLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page1_ManagerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page1_ManagerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page1_ManagerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page1_ManagerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page1_ManagerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackToHomePage;
    private javax.swing.JButton btnLogin;
    private javax.swing.JTextField emailLine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JTextField passwordLine;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
