/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.Manager;

import com.mycompany.Database.AdminPageLogout;
import com.mycompany.Database.DBConnection;
import com.mycompany.Database.ManagerCredentials;
import com.mycompany.Database.ManagerPageLogout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JoeAlpha
 */
public class Page3_Rooms extends javax.swing.JFrame implements Runnable {
    SimpleDateFormat timeFormat;// setting variable for time Format
    SimpleDateFormat dayFormat;// setting variable for day Format
    SimpleDateFormat dateFormat;// setting variable for date Format
    String time; // setting variable for current time
    String day; // setting variable for day
    String date; // setting variable for date
    
    
    /**
     * Creates new form Page2_Dashboard
     */
    public Page3_Rooms() {
        initComponents();
        rooms_table();

        // center the form
        this.setLocationRelativeTo(this);
        
        Thread t = new Thread(this);
        t.start();
        
        txtForSearch.setVisible(true);
        btnSearch.setVisible(true);
        
        // displaying users info
        sideBarFname.setText(ManagerCredentials.fullname);
        sideBarOperator.setText(ManagerCredentials.operator_id); 
        topBarRegNo.setText(ManagerCredentials.serial_no);
    }
    
    
    DefaultTableModel defaulttbl_1_query;
    DefaultTableModel defaulttbl_2_delete;
    
    PreparedStatement sqlQueryCheck;
    PreparedStatement sqlQueryInsert;
    PreparedStatement sqlQueryLogout;
    ResultSet res;
    Connection conn;
    
    
    private void rooms_table() {
        try {
            conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_rooms");
            res = sqlQueryCheck.executeQuery();
            
            while(res.next()) {
                String rmId     = res.getString("id");
                String rmNumber = res.getString("room_no");
                String rmType   = res.getString("room_type");
                String rmBed    = res.getString("bed");
                String rmPrice  = res.getString("price");
                String rmStatus = res.getString("status");
                
                Object[] obj = {rmId, rmNumber, rmType, rmBed, rmPrice, rmStatus};
                
                defaulttbl_1_query = (DefaultTableModel)tbl_rooms.getModel();
                defaulttbl_1_query.addRow(obj);
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Rooms.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        topBarRegNo = new javax.swing.JLabel();
        txtDay = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        btnShowAll = new javax.swing.JButton();
        btnAddStud = new javax.swing.JButton();
        btnDelMg = new javax.swing.JButton();
        txtForSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_rooms = new rojeru_san.complementos.RSTableMetro();
        jPanel8 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        priceLine = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtRoomType = new javax.swing.JComboBox<>();
        jPanel23 = new javax.swing.JPanel();
        btnAddRoom = new javax.swing.JButton();
        btnClearForm = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        serialLine = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRoomNo = new javax.swing.JTextField();
        errorRoom = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtBed = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        sideBarFname = new javax.swing.JLabel();
        sideBarOperator = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        GoToLogout = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        goToDashbord = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        goToSettings = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        goToRooms = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        goToCustomers = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        goToReport = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(java.awt.Color.white);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel17.setText("Manage Rooms");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 30));

        topBarRegNo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jPanel10.add(topBarRegNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 60, 120, 17));

        txtDay.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtDay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel10.add(txtDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 30, 100, 17));

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel24.setForeground(java.awt.SystemColor.windowBorder);
        jLabel24.setText("Serial No:");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtTime.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel10.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 90, 17));

        txtDate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel10.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 100, 17));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1, 648, 90));

        jPanel25.setOpaque(false);
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnShowAll.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnShowAll.setText("Show All");
        btnShowAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });
        jPanel25.add(btnShowAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        btnAddStud.setBackground(java.awt.SystemColor.textHighlight);
        btnAddStud.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAddStud.setForeground(java.awt.Color.white);
        btnAddStud.setText("Add");
        btnAddStud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudActionPerformed(evt);
            }
        });
        jPanel25.add(btnAddStud, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 70, 30));

        btnDelMg.setBackground(java.awt.Color.red);
        btnDelMg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnDelMg.setForeground(java.awt.Color.white);
        btnDelMg.setText("Delete");
        btnDelMg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelMg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelMgActionPerformed(evt);
            }
        });
        jPanel25.add(btnDelMg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 70, 30));

        txtForSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtForSearch.setForeground(java.awt.Color.gray);
        txtForSearch.setText("search by room no/bed");
        txtForSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));
        txtForSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtForSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtForSearchFocusLost(evt);
            }
        });
        jPanel25.add(txtForSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 0, 200, 30));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setOpaque(true);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        jPanel25.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 2, 30, 26));

        jPanel1.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 105, 590, 32));

        jPanel11.setBackground(java.awt.Color.white);
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(java.awt.Color.white);

        tbl_rooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Room No", "Type", "Bed", "Price", "Status"
            }
        ));
        tbl_rooms.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tbl_rooms.setColorBordeHead(new java.awt.Color(0, 112, 192));
        tbl_rooms.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_rooms.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_rooms.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_rooms.setFuenteFilas(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_rooms.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_rooms.setFuenteHead(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tbl_rooms.setGrosorBordeFilas(0);
        tbl_rooms.setGrosorBordeHead(0);
        tbl_rooms.setMultipleSeleccion(false);
        tbl_rooms.setRowHeight(25);
        tbl_rooms.setShowHorizontalLines(false);
        tbl_rooms.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tbl_rooms);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel15);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel29.setOpaque(false);
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(java.awt.Color.white);
        jPanel13.setOpaque(false);
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        priceLine.setBackground(java.awt.Color.darkGray);
        priceLine.setText("jTextField2");
        priceLine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel13.add(priceLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 33, 220, 1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        jPanel13.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtPrice.setForeground(java.awt.Color.gray);
        txtPrice.setText("price(ksh)");
        txtPrice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPriceFocusLost(evt);
            }
        });
        jPanel13.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 3, 185, 25));

        jPanel29.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 230, 53));

        jPanel21.setBackground(java.awt.Color.white);
        jPanel21.setOpaque(false);
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel10.setText("Room Type:");
        jPanel21.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, -1));

        txtRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Executive", "Mini Suite" }));
        jPanel21.add(txtRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 23, 230, 30));

        jPanel29.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 230, 53));

        jPanel23.setBackground(java.awt.Color.white);
        jPanel23.setOpaque(false);
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddRoom.setBackground(java.awt.SystemColor.textHighlight);
        btnAddRoom.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnAddRoom.setForeground(java.awt.Color.white);
        btnAddRoom.setText("Register");
        btnAddRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });
        jPanel23.add(btnAddRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 96, 30));

        btnClearForm.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnClearForm.setText("Clear");
        btnClearForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFormActionPerformed(evt);
            }
        });
        jPanel23.add(btnClearForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 0, 96, 30));

        jPanel29.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 230, 30));

        jPanel20.setBackground(java.awt.Color.white);
        jPanel20.setOpaque(false);
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serialLine.setBackground(java.awt.Color.darkGray);
        serialLine.setText("jTextField2");
        serialLine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel20.add(serialLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 33, 220, 1));
        jPanel20.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        txtRoomNo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtRoomNo.setForeground(java.awt.Color.gray);
        txtRoomNo.setText("room no.(123)");
        txtRoomNo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        txtRoomNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRoomNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRoomNoFocusLost(evt);
            }
        });
        txtRoomNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRoomNoKeyReleased(evt);
            }
        });
        jPanel20.add(txtRoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 3, 185, 25));

        errorRoom.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorRoom.setForeground(java.awt.Color.red);
        jPanel20.add(errorRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 226, 18));

        jPanel29.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 230, 53));

        jPanel22.setBackground(java.awt.Color.white);
        jPanel22.setOpaque(false);
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel22.setText("Bed:");
        jPanel22.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, -1));

        txtBed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple", "Quad", "Twin Beds" }));
        jPanel22.add(txtBed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 23, 230, 30));

        jPanel29.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 230, 53));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Add New Room");
        jPanel29.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 586, 30));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab2", jPanel8);

        jPanel11.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 590, 420));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 145, 590, 390));

        jPanel2.setBackground(java.awt.SystemColor.textHighlight);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Greens");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 0, 70, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Milimani");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, 170, -1));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBarFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sideBarFname.setForeground(java.awt.Color.white);
        jPanel4.add(sideBarFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1, 130, 20));

        sideBarOperator.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sideBarOperator.setForeground(java.awt.Color.white);
        jPanel4.add(sideBarOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 21, 130, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/holder1.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 40, 40));

        jLabel6.setBackground(java.awt.Color.white);
        jLabel6.setOpaque(true);
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 50, 170, 1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 60));

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 30, 25));

        GoToLogout.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        GoToLogout.setForeground(java.awt.Color.white);
        GoToLogout.setText("Logout");
        GoToLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        GoToLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GoToLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoToLogoutMouseClicked(evt);
            }
        });
        jPanel5.add(GoToLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 2, -1, 25));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 150, 30));

        jPanel6.setBackground(java.awt.Color.white);
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manager.png"))); // NOI18N
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 30, 25));

        goToDashbord.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        goToDashbord.setForeground(new java.awt.Color(255, 255, 255));
        goToDashbord.setText("Dashboard");
        goToDashbord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goToDashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToDashbordMouseClicked(evt);
            }
        });
        jPanel6.add(goToDashbord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 5, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, 30));

        jPanel16.setBackground(java.awt.Color.white);
        jPanel16.setOpaque(false);
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/settings.png"))); // NOI18N
        jPanel16.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 30, 25));

        goToSettings.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        goToSettings.setForeground(new java.awt.Color(255, 255, 255));
        goToSettings.setText("Settings");
        goToSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goToSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToSettingsMouseClicked(evt);
            }
        });
        jPanel16.add(goToSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 5, -1, -1));

        jPanel2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 150, 30));

        jPanel17.setBackground(java.awt.Color.white);
        jPanel17.setOpaque(false);
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        jPanel17.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 30, 25));

        goToRooms.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        goToRooms.setForeground(new java.awt.Color(255, 255, 255));
        goToRooms.setText("Rooms");
        goToRooms.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goToRooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToRoomsMouseClicked(evt);
            }
        });
        jPanel17.add(goToRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 5, -1, -1));

        jPanel2.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 150, 30));

        jPanel18.setBackground(java.awt.Color.white);
        jPanel18.setOpaque(false);
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Student.png"))); // NOI18N
        jPanel18.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 30, 25));

        goToCustomers.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        goToCustomers.setForeground(new java.awt.Color(255, 255, 255));
        goToCustomers.setText("Customers");
        goToCustomers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goToCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToCustomersMouseClicked(evt);
            }
        });
        jPanel18.add(goToCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 5, -1, -1));

        jPanel2.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 150, 30));

        jPanel19.setBackground(java.awt.Color.white);
        jPanel19.setOpaque(false);
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile.png"))); // NOI18N
        jPanel19.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 30, 25));

        goToReport.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        goToReport.setForeground(new java.awt.Color(255, 255, 255));
        goToReport.setText("Report");
        goToReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goToReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToReportMouseClicked(evt);
            }
        });
        jPanel19.add(goToReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 5, -1, -1));

        jPanel2.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        
        txtForSearch.setVisible(true);
        btnSearch.setVisible(true);
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnAddStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        
        txtForSearch.setVisible(false);
        btnSearch.setVisible(false);
    }//GEN-LAST:event_btnAddStudActionPerformed

    private void btnDelMgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelMgActionPerformed
        // Operation for deleting manager account
        try {
            defaulttbl_2_delete = (DefaultTableModel)tbl_rooms.getModel();
            int selectIndex = tbl_rooms.getSelectedRow();

            int id = Integer.parseInt(defaulttbl_2_delete.getValueAt(selectIndex, 0).toString());

            // confirmation message
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to Delete this Room", "Warnimg", JOptionPane.YES_NO_OPTION);

            if(dialogResult == JOptionPane.YES_OPTION){
                try {
                    Connection conn = DBConnection.setConnection();
                    sqlQueryCheck = conn.prepareStatement("delete from tbl_rooms where id=?");
                    sqlQueryCheck.setInt(1, id);
                    sqlQueryCheck.executeUpdate();

                    JOptionPane.showMessageDialog(null, "The Room has been Deleted Successfully");

                    rooms_table();

                    // refreshing the current page
                    new Page3_Rooms().setVisible(true);
                    this.dispose();
                } catch (Exception ex) {
                    Logger.getLogger(Page3_Rooms.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No Room has been selected!", "Warnimg", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDelMgActionPerformed

    private void txtRoomNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRoomNoFocusGained
        if(txtRoomNo.getText().trim().toLowerCase().equals("room no.(123)")){
            txtRoomNo.setText("");
            txtRoomNo.setForeground(Color.black);
            serialLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtRoomNoFocusGained

    private void txtRoomNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRoomNoFocusLost
        if(txtRoomNo.getText().trim().equals("") || txtRoomNo.getText().trim().equals("room no.(123)")){
            txtRoomNo.setText("room no.(123)");
            txtRoomNo.setForeground(Color.gray);
            serialLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtRoomNoFocusLost

    private void txtRoomNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRoomNoKeyReleased
        String PATTERN = "^[a-z A-Z 0-9/]{0,10}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtRoomNo.getText());

        if(!match.matches()) {
            errorRoom.setText("Invalid Reg No!");
        } else {
            errorRoom.setText(null);
        }
    }//GEN-LAST:event_txtRoomNoKeyReleased

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
        // operation of createing a new account
        String room   = txtRoomNo.getText();
        String type   = txtRoomType.getSelectedItem().toString();
        String bed    = txtBed.getSelectedItem().toString();
        String price  = txtPrice.getText();
        String status = "Available";

        try {
            conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_rooms where room_no=? ");
            sqlQueryCheck.setString(1, room);
            res = sqlQueryCheck.executeQuery();

            if(res.isBeforeFirst()) {
                // if the credential already exist display error message
                JOptionPane.showMessageDialog(this, "There is a Room with this number already", "Please use new Room No", JOptionPane.ERROR_MESSAGE);

                // clearing neccessary fields to allow the admin to re-enter new Cridentials
                txtRoomNo.setText("");
                errorRoom.setText(null);
                if(txtRoomNo.getText().trim().equals("")){
                    txtRoomNo.setText("room no.(123)");
                    txtRoomNo.setForeground(Color.gray);
                    serialLine.setBackground(Color.black);
                }

                return;
            }else {
                sqlQueryInsert = conn.prepareStatement("insert into tbl_rooms (room_no,room_type,bed,price,status) values (?,?,?,?,?) ");
                sqlQueryInsert.setString(1, room);
                sqlQueryInsert.setString(2, type);
                sqlQueryInsert.setString(3, bed);
                sqlQueryInsert.setString(4, price);
                sqlQueryInsert.setString(5, status);

                //if the record is inserted successfully the state of executeUpdate() will be 1
                if (sqlQueryInsert.executeUpdate() != 0) {
                    JOptionPane.showMessageDialog(null, "A New Room has been added successfully.");

                    // clearing the form after successfully adding the new record in the database
                    txtRoomNo.setText("");
                    errorRoom.setText(null);
                    if(txtRoomNo.getText().trim().equals("")){
                        txtRoomNo.setText("room no.(123)");
                        txtRoomNo.setForeground(Color.gray);
                        serialLine.setBackground(Color.black);
                    }
                    
                    txtPrice.setText("");
                    if(txtPrice.getText().trim().equals("")){
                        txtPrice.setText("price(ksh)");
                        txtPrice.setForeground(Color.gray);
                        priceLine.setBackground(Color.black);
                    }

                    // refresh the page
                    new Page3_Rooms().setVisible(true);
                    this.dispose();

                    return;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Rooms.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void btnClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFormActionPerformed
        txtRoomNo.setText("");
        errorRoom.setText(null);
        if(txtRoomNo.getText().trim().equals("")){
            txtRoomNo.setText("room no.(123)");
            txtRoomNo.setForeground(Color.gray);
            serialLine.setBackground(Color.black);
        }
        
        txtPrice.setText("");
        if(txtPrice.getText().trim().equals("")){
            txtPrice.setText("price(ksh)");
            txtPrice.setForeground(Color.gray);
            priceLine.setBackground(Color.black);
        }
        
        txtRoomNo.requestFocus();
    }//GEN-LAST:event_btnClearFormActionPerformed

    private void txtPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusGained
        if(txtPrice.getText().trim().toLowerCase().equals("price(ksh)")){
            txtPrice.setText("");
            txtPrice.setForeground(Color.black);
            priceLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtPriceFocusGained

    private void txtPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusLost
        if(txtPrice.getText().trim().equals("") || txtPrice.getText().trim().equals("price(ksh)")){
            txtPrice.setText("price(ksh)");
            txtPrice.setForeground(Color.gray);
            priceLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtPriceFocusLost

    private void txtForSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtForSearchFocusGained
        // operation that occur when this field is clicked
        if(txtForSearch.getText().trim().toLowerCase().equals("search by room no/bed")){
            txtForSearch.setText("");
            txtForSearch.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtForSearchFocusGained

    private void txtForSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtForSearchFocusLost
        // operation that occur when this field is not clicked
        if(txtForSearch.getText().trim().equals("") || txtForSearch.getText().trim().equals("search by room no/bed")){
            txtForSearch.setText("search by room no/bed");
            txtForSearch.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtForSearchFocusLost

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // function for searching specific record
        String RoomOrBed = txtForSearch.getText();

        try {
            conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_rooms where room_no like '%"+RoomOrBed+"%' or bed like '%"+RoomOrBed+"%' ");
            res = sqlQueryCheck.executeQuery();

            DefaultTableModel model = (DefaultTableModel)tbl_rooms.getModel();
            model.setRowCount(0);

            try {
                while(res.next()) {
                    model.addRow(new Object[]{
                        res.getString(1),
                        res.getString(2),
                        res.getString(3),
                        res.getString(4),
                        res.getString(5),
                        res.getString(6)
                    });
                }

                res.close();
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        catch (Exception ex) {
            Logger.getLogger(Page3_Rooms.class.getName()).log(Level.SEVERE,null, ex);
        }
    }//GEN-LAST:event_btnSearchMouseClicked

    private void GoToLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoToLogoutMouseClicked
        // operation for login out
        String SerialNo = topBarRegNo.getText();

        try {
            conn = DBConnection.setConnection();
            sqlQueryLogout = conn.prepareStatement("update tbl_managers SET status='Offline' WHERE serial_no=? ");
            sqlQueryLogout.setString(1, SerialNo);

            //if the logout is successfully the state of executeUpdate() will be 1
            if (sqlQueryLogout.executeUpdate() != 0) {
                // redirect to login
                Page1_ManagerLogin login = new Page1_ManagerLogin();

                // logout function
                ManagerPageLogout.logMeOut(this, login);
            }
        } catch (Exception ex) {
            Logger.getLogger(Page2_Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GoToLogoutMouseClicked

    private void goToDashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToDashbordMouseClicked
        // Go to dashboard
        Page2_Dashboard dash = new Page2_Dashboard();
        this.dispose();
        dash.setVisible(true);
    }//GEN-LAST:event_goToDashbordMouseClicked

    private void goToSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToSettingsMouseClicked
        // Go to settings
        Page6_Settings settings = new Page6_Settings();
        this.dispose();
        settings.setVisible(true);
    }//GEN-LAST:event_goToSettingsMouseClicked

    private void goToRoomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToRoomsMouseClicked
        // Go to rooms
        Page3_Rooms rooms = new Page3_Rooms();
        this.dispose();
        rooms.setVisible(true);
    }//GEN-LAST:event_goToRoomsMouseClicked

    private void goToCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToCustomersMouseClicked
        // Go to customers
        Page4_Customer customers = new Page4_Customer();
        this.dispose();
        customers.setVisible(true);
    }//GEN-LAST:event_goToCustomersMouseClicked

    private void goToReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToReportMouseClicked
        // Go to report
        Page5_Report report = new Page5_Report();
        this.dispose();
        report.setVisible(true);
    }//GEN-LAST:event_goToReportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page3_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page3_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page3_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page3_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page3_Rooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GoToLogout;
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnAddStud;
    private javax.swing.JButton btnClearForm;
    private javax.swing.JButton btnDelMg;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JLabel errorRoom;
    private javax.swing.JLabel goToCustomers;
    private javax.swing.JLabel goToDashbord;
    private javax.swing.JLabel goToReport;
    private javax.swing.JLabel goToRooms;
    private javax.swing.JLabel goToSettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField priceLine;
    private javax.swing.JTextField serialLine;
    private javax.swing.JLabel sideBarFname;
    private javax.swing.JLabel sideBarOperator;
    private rojeru_san.complementos.RSTableMetro tbl_rooms;
    private javax.swing.JLabel topBarRegNo;
    private javax.swing.JComboBox<String> txtBed;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtDay;
    private javax.swing.JTextField txtForSearch;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRoomNo;
    private javax.swing.JComboBox<String> txtRoomType;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true) {
            try {
                timeFormat = new SimpleDateFormat("hh:mm:ss a");
                time = timeFormat.format(Calendar.getInstance().getTime());
                txtTime.setText(time);

                dayFormat = new SimpleDateFormat("EEEE");
                day = dayFormat.format(Calendar.getInstance().getTime());
                txtDay.setText(day);

                dateFormat = new SimpleDateFormat("dd MMM yyyy"); // setting the time
                date = dateFormat.format(Calendar.getInstance().getTime());// getting current date
                txtDate.setText(date);// displaying the date to the user
            }
            catch(Exception e) {
                e.printStackTrace();
            }
        }
    }
}
